import { AdminProvider } from './context/AdminContext'
import { UserProvider } from './context/UserContext'
import './globals.css'
import { Unna } from 'next/font/google'

const unna = Unna({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-unna',

})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <UserProvider>
      <AdminProvider>
        <html lang="pt-br">
          <body className={`$${unna.variable} font-sans`}>{children}</body>
        </html>
      </AdminProvider>
    </UserProvider>
  )
}
